config/routes.rb
DeviseTest::Application.routes.draw do

  devise_for :users, :controllers => { :passwords => 'passwords' }

  
  scope :controller => :dashboard do
    root :to => :home
    match "/home" => :home
    match "/contact" => :contact
    match "/users" => :all_users, :as => 'all_users'
    match "/profile" => :profile
  end
  
  scope :controller => :appointments do
    match "/schedule" => :list
  end
  
  resources :user, :controller => "user"

end

app/models/ability.rb
class Ability
  include CanCan::Ability
  
  def initialize(user)
    can :read, :all
    #guest user
    user ||= User.new
    
    if user.role? :super_admin
      can :manage, :all
    else
      # restrict to specific actions in the contoller
      can [:home, :contact, :profile], :dashboard
    end
  end
end

app/models/role.rb
class Role < ActiveRecord::Base
  
  attr_accessible :name
  
  has_and_belongs_to_many :user
  
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :admin, :photo
  
  # setup multiple roles
  has_and_belongs_to_many :roles
  
  has_attached_file :photo
  
  def role?(role)
    return !!self.roles.find_by_name(role.to_s.camelize)
  end
  
  def all_roles
    self.roles.find(:all).collect{ |role| role.name }
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
  rescue_from CanCan::AccessDenied do |exception|
    Rails.logger.debug "Access denied on #{exception.action} #{exception.subject.inspect}"
    flash[:error] = "Access Denied"
    redirect_to root_path
  end
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  def list
  end

end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  # activate access control with cancan at the controller level
  authorize_resource :class => false

  def home
  end

  def contact
  end
  
  def all_users
    @users = User.find(:all, :conditions => ["id IS NOT (?)", current_user.id])
    # authorize! :manage, User
  end
  
  def profile
    @user = current_user
  end

end

app/controllers/passwords_controller.rb
class PasswordsController < ApplicationController
  before_filter :authenticate_user!
  
  def edit
    @user = current_user
  end
  
  def update
    @user = current_user
    
    res = @user.update_with_password(params[:user])
    logger.info "Password update result: #{res.inspect}"
    
    if res
      sign_in(@user, :bypass => true)
      redirect_to root_path, :notice => "password updated!"
    else
      render :edit
    end
  end
  
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  load_and_authorize_resource
  
  def index
    @users = User.find(:all, :conditions => ['id IS NOT (?)', current_user.id])
  end
  
  def show
    @user = current_user
  end
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(params[:user])
    if @user.save
      flash[:notice] = "Succussfully created User."
      redirect_to root_path
    else
      render :action => "new"
    end
  end
  
  def edit
    @user = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])
    params[:user].delete(:password) if params[:user][:password].blank?
    params[:user].delete(:password_confirmation) if params[:user][:password].blank? and params[:user][:password_confirmation].blank?
    if @user.update_attributes(params[:user])
      flash[:notice] = "Successfully updated user"
      redirect_to root_path
    else
      render :action => "edit"
    end
  end
  
  def destroy
    @user = User.find(params[:id])
    if @user.destroy
      flash[:notice] = "Successfully deleted User."
      redirect_to root_path
    end
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/passwords_helper.rb
module PasswordsHelper
  
  def resource_name
    :user
  end
  
  def resource
    @resource ||= current_user
  end
  
  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
  
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/appointments/list.html.erb
<h1>My Schedule</h1>

<div id='calendar'>
</div>

app/views/dashboard/all_users.html.erb
<% for user in @users %>
  <p>Email: <%= user.email %>, <%= image_tag user.photo.url %>
    <% if can? :manage, user %>
      <%= link_to "Edit User", edit_user_path(user) %>,
      <%= link_to "Delete User", user_path(user), :confirm => "Are you sure?", :method => :delete %>
  </p>
    <% end %>
<% end %>

<% if can? :manage, user %>
  <p><%= link_to "Add User", new_user_path %></p>
<% end %>

app/views/dashboard/contact.html.erb
<h1>Contact Page</h1>
<p>Find me in app/views/dashboard/contact.html.erb</p>

app/views/dashboard/home.html.erb
<h1>This is your Home Page</h1>

<% if user_signed_in? %>
  
  <% if current_user.role? :super_admin %>
    <p>Hello Super-Admin - with great power comes great responsability!</p>
  <% end %>
  <p>User roles: <%= current_user.all_roles %></p>
  <ul>
    <li><%= link_to "show profile", profile_path %>
    <li><%= link_to "edit profile", edit_user_registration_path %>
    <li><%= link_to "sign out", destroy_user_session_path, :method => :delete %></li>
    <li><%= link_to "change password", edit_user_password_path %></li>
    <li><%= link_to "all users", all_users_path %></li>
    <li><%= link_to "my schedule", schedule_path %></li>
  </ul>
<% else %>
  <ul>
    <li><%= link_to "sign in", new_user_session_path %></li>
    <li><%= link_to "recover password", new_user_password_path %></li>
  </ul>
<% end %>

app/views/dashboard/profile.html.erb
<p>Email: <br />
<%= @user.email %></p>

<p><%= image_tag @user.photo.url %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DeviseTest</title>
  <%= stylesheet_link_tag :all %>
  <%= stylesheet_link_tag "fullcalendar"%>
  <%= stylesheet_link_tag "fullcalendar.print"%>
  <%= stylesheet_link_tag "calendar" %>
  <%= javascript_include_tag :defaults %>
  <%= javascript_include_tag "fullcalendar" %>
  <%= javascript_include_tag "fullcalendar.min" %>
  <%= javascript_include_tag "gcal" %>
  <%= csrf_meta_tag %>
</head>
<body>

<p class="notice"><%= flash[:notice] %></p>
<p class="alert"><%= flash[:alert] %></p>
<p class="error"><%= flash[:error] %></p>
       
<%= yield %>

<%= debug(params) if Rails.env.development? %>
</body>
</html>

app/views/user/_form.html.erb
<p><%= f.label :email %><br />
<%= f.text_field :email %></p>

<p><%= f.label :password %><br />
<%= f.password_field :password %></p>

<p><%= f.label :password_confirmation %><br />
<%= f.password_field :password_confirmation %></p>

<p><%= f.file_field :photo %></p>

<p><%= f.submit "Submit" %></p>

app/views/user/edit.html.erb
<h2>Edit User</h2>

<%= form_for @user, :url => user_path, :html => { :multipart => true } do |f| %>
  <%= render :partial => 'form', :locals => { :f => f } %>
<% end %>

app/views/user/new.html.erb
<h1>New User</h1>

<%= form_for @user, :url => user_index_path do |f| %>
  <%= render :partial => 'form', :locals => { :f => f } %>
<% end %>

app/views/user/show.html.erb
<p>Email: <br />
<%= @user.email %></p>

<p><%= image_tag @user.photo.url %></p>

<p><%= f.submit "Submit" %></p>